development: &development
  adapter: postgresql
  encoding: unicode
  database: test_app_development
  host: localhost
  pool: 5
  username: idt_web
  password: JR-test

test:
  <<: *development
  host: localhost
  username: pguser
  database: test_app_test

production: 
  <<: *development
  database: test_app_production



